server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresqldb://postgresqldb:5432/employee-management-db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl: create